/**
 * Monaco snippet templates for the FinOps FOCUS domain.
 * See design spec §5.2 and §6.2.
 */

import type { RegoSnippet } from '@develapp/opa-domain-contract';

export const finopsSnippets: RegoSnippet[] = [
  {
    label: 'Deny expensive service',
    description:
      'Deny a charge when EffectiveCost exceeds a threshold for a service',
    body: [
      '# METADATA',
      '# schemas:',
      '#   - input: schema["finops-focus"]',
      'package finops.costmodel.expensive',
      '',
      'default deny := false',
      '',
      'deny if {',
      '  input.ServiceName == "${1:AWS EC2}"',
      '  input.EffectiveCost > ${2:10000}',
      '}',
      '',
      'default allow := true',
      '',
      'allow if { not deny }',
      '',
      'report[msg] if {',
      '  input.ServiceName == "${1:AWS EC2}"',
      '  input.EffectiveCost > ${2:10000}',
      '  msg := sprintf("expensive service %s: cost %v", [input.ServiceName, input.EffectiveCost])',
      '}',
    ].join('\n'),
  },
  {
    label: 'Aggregate effective cost by service',
    description: 'Report total effective cost grouped by service name',
    body: [
      '# METADATA',
      '# schemas:',
      '#   - input: schema["finops-focus"]',
      'package finops.costmodel.aggregate',
      '',
      'report[service] := cost if {',
      '  service := input.ServiceName',
      '  cost := input.EffectiveCost',
      '}',
      '',
      'default allow := true',
      'default deny := false',
      '',
      'deny if { input.EffectiveCost > 0 && input.BillingCurrency == "" }',
    ].join('\n'),
  },
  {
    label: 'Flag idle resources',
    description: 'Deny or flag resources with Idle status and non-zero cost',
    body: [
      '# METADATA',
      '# schemas:',
      '#   - input: schema["finops-focus"]',
      'package finops.costmodel.idle',
      '',
      'default deny := false',
      '',
      'deny if {',
      '  input.ResourceStatus == "Idle"',
      '  input.EffectiveCost > 0',
      '}',
      '',
      'default allow := true',
      'allow if { not deny }',
      '',
      'report[msg] if {',
      '  input.ResourceStatus == "Idle"',
      '  input.EffectiveCost > 0',
      '  msg := sprintf("idle resource %s costs %v %s", [input.ResourceId, input.EffectiveCost, input.BillingCurrency])',
      '}',
    ].join('\n'),
  },
  {
    label: 'Currency mismatch check',
    description: 'Deny when billing currency is not in the allowed set',
    body: [
      '# METADATA',
      '# schemas:',
      '#   - input: schema["finops-focus"]',
      'package finops.costmodel.currency',
      '',
      'allowed_currencies := {"USD", "EUR", "DKK"}',
      '',
      'default deny := false',
      'deny if {',
      '  not allowed_currencies[input.BillingCurrency]',
      '}',
      '',
      'default allow := true',
      'allow if { not deny }',
      '',
      'report[msg] if {',
      '  not allowed_currencies[input.BillingCurrency]',
      '  msg := sprintf("unexpected currency: %s", [input.BillingCurrency])',
      '}',
    ].join('\n'),
  },
];
